In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('insurance_defaulter_prediction/train_jRxnrHD.csv')

In [3]:
df.head()

id  perc_premium_paid_by_cash_credit  age_in_days  Income  \
0  110936                             0.429        12058  355060   
1   41492                             0.010        21546  315150   
2   31300                             0.917        17531   84140   
3   19415                             0.049        15341  250510   
4   99379                             0.052        31400  198680   

   Count_3-6_months_late  Count_6-12_months_late  \
0                    0.0                     0.0   
1                    0.0                     0.0   
2                    2.0                     3.0   
3                    0.0                     0.0   
4                    0.0                     0.0   

   Count_more_than_12_months_late  application_underwriting_score  \
0                             0.0                           99.02   
1                             0.0                           99.89   
2                             1.0                           98.69   
3                             0.0                           99.57   
4                             0.0                           99.87   

   no_of_premiums_paid sourcing_channel residence_area_type  premium  target  
0                   13                C               Urban     3300       1  
1                   21                A               Urban    18000       1  
2                    7                C               Rural     3300       0  
3                    9                A               Urban     9600       1  
4                   12                B               Urban     9600       1

In [4]:
df.shape

(79853, 13)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79853 entries, 0 to 79852
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   id                                79853 non-null  int64  
 1   perc_premium_paid_by_cash_credit  79853 non-null  float64
 2   age_in_days                       79853 non-null  int64  
 3   Income                            79853 non-null  int64  
 4   Count_3-6_months_late             79756 non-null  float64
 5   Count_6-12_months_late            79756 non-null  float64
 6   Count_more_than_12_months_late    79756 non-null  float64
 7   application_underwriting_score    76879 non-null  float64
 8   no_of_premiums_paid               79853 non-null  int64  
 9   sourcing_channel                  79853 non-null  object 
 10  residence_area_type               79853 non-null  object 
 11  premium                           79853 non-null  int64  
 12  targ

# preprocessing

In [6]:
df.isnull().sum()

id                                     0
perc_premium_paid_by_cash_credit       0
age_in_days                            0
Income                                 0
Count_3-6_months_late                 97
Count_6-12_months_late                97
Count_more_than_12_months_late        97
application_underwriting_score      2974
no_of_premiums_paid                    0
sourcing_channel                       0
residence_area_type                    0
premium                                0
target                                 0
dtype: int64

In [7]:
df.duplicated().sum()

0

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.shape

(79853, 13)

In [10]:
df.drop(['id'], axis=1, inplace=True)

In [11]:
df.shape

(79853, 12)

# one hot encoding

In [12]:
df_ohe = pd.get_dummies(df)

In [13]:
df_ohe.shape

(79853, 17)

In [14]:
df_ohe.isnull().sum()

perc_premium_paid_by_cash_credit       0
age_in_days                            0
Income                                 0
Count_3-6_months_late                 97
Count_6-12_months_late                97
Count_more_than_12_months_late        97
application_underwriting_score      2974
no_of_premiums_paid                    0
premium                                0
target                                 0
sourcing_channel_A                     0
sourcing_channel_B                     0
sourcing_channel_C                     0
sourcing_channel_D                     0
sourcing_channel_E                     0
residence_area_type_Rural              0
residence_area_type_Urban              0
dtype: int64

In [15]:
df_ohe.fillna(df_ohe.median(), inplace=True)

In [16]:
df_ohe.isnull().sum()

perc_premium_paid_by_cash_credit    0
age_in_days                         0
Income                              0
Count_3-6_months_late               0
Count_6-12_months_late              0
Count_more_than_12_months_late      0
application_underwriting_score      0
no_of_premiums_paid                 0
premium                             0
target                              0
sourcing_channel_A                  0
sourcing_channel_B                  0
sourcing_channel_C                  0
sourcing_channel_D                  0
sourcing_channel_E                  0
residence_area_type_Rural           0
residence_area_type_Urban           0
dtype: int64

In [17]:
df_ohe.columns

Index(['perc_premium_paid_by_cash_credit', 'age_in_days', 'Income',
       'Count_3-6_months_late', 'Count_6-12_months_late',
       'Count_more_than_12_months_late', 'application_underwriting_score',
       'no_of_premiums_paid', 'premium', 'target', 'sourcing_channel_A',
       'sourcing_channel_B', 'sourcing_channel_C', 'sourcing_channel_D',
       'sourcing_channel_E', 'residence_area_type_Rural',
       'residence_area_type_Urban'],
      dtype='object')

In [18]:
df_ohe.nunique()

perc_premium_paid_by_cash_credit     1001
age_in_days                           833
Income                              24165
Count_3-6_months_late                  14
Count_6-12_months_late                 17
Count_more_than_12_months_late         10
application_underwriting_score        672
no_of_premiums_paid                    57
premium                                30
target                                  2
sourcing_channel_A                      2
sourcing_channel_B                      2
sourcing_channel_C                      2
sourcing_channel_D                      2
sourcing_channel_E                      2
residence_area_type_Rural               2
residence_area_type_Urban               2
dtype: int64

In [19]:
df_ohe.dtypes

perc_premium_paid_by_cash_credit    float64
age_in_days                           int64
Income                                int64
Count_3-6_months_late               float64
Count_6-12_months_late              float64
Count_more_than_12_months_late      float64
application_underwriting_score      float64
no_of_premiums_paid                   int64
premium                               int64
target                                int64
sourcing_channel_A                     bool
sourcing_channel_B                     bool
sourcing_channel_C                     bool
sourcing_channel_D                     bool
sourcing_channel_E                     bool
residence_area_type_Rural              bool
residence_area_type_Urban              bool
dtype: object

# X & Y split

In [20]:
X = df_ohe.drop(['premium','target'], axis=1)
X.head()

perc_premium_paid_by_cash_credit  age_in_days  Income  \
0                             0.429        12058  355060   
1                             0.010        21546  315150   
2                             0.917        17531   84140   
3                             0.049        15341  250510   
4                             0.052        31400  198680   

   Count_3-6_months_late  Count_6-12_months_late  \
0                    0.0                     0.0   
1                    0.0                     0.0   
2                    2.0                     3.0   
3                    0.0                     0.0   
4                    0.0                     0.0   

   Count_more_than_12_months_late  application_underwriting_score  \
0                             0.0                           99.02   
1                             0.0                           99.89   
2                             1.0                           98.69   
3                             0.0                           99.57   
4                             0.0                           99.87   

   no_of_premiums_paid  sourcing_channel_A  sourcing_channel_B  \
0                   13               False               False   
1                   21                True               False   
2                    7               False               False   
3                    9                True               False   
4                   12               False                True   

   sourcing_channel_C  sourcing_channel_D  sourcing_channel_E  \
0                True               False               False   
1               False               False               False   
2                True               False               False   
3               False               False               False   
4               False               False               False   

   residence_area_type_Rural  residence_area_type_Urban  
0                      False                       True  
1                      False                       True  
2                       True                      False  
3                      False                       True  
4                      False                       True

In [21]:
Y = df_ohe['target']
Y.head()

0    1
1    1
2    0
3    1
4    1
Name: target, dtype: int64

In [22]:
X.shape, Y.shape

((79853, 15), (79853,))

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=7, )

In [24]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((55897, 15), (23956, 15), (55897,), (23956,))

# Standardization

In [25]:
from sklearn.preprocessing import StandardScaler
sd = StandardScaler()
sd.fit(X_train, Y_train)

StandardScaler()

In [26]:
X_train.describe()

perc_premium_paid_by_cash_credit   age_in_days        Income  \
count                      55897.000000  55897.000000  5.589700e+04   
mean                           0.313552  18845.565093  2.081529e+05   
std                            0.334074   5209.204715  4.066187e+05   
min                            0.000000   7670.000000  2.403000e+04   
25%                            0.034000  14974.000000  1.078300e+05   
50%                            0.168000  18626.000000  1.670500e+05   
75%                            0.535000  22636.000000  2.525900e+05   
max                            1.000000  37602.000000  5.382190e+07   

       Count_3-6_months_late  Count_6-12_months_late  \
count           55897.000000            55897.000000   
mean                0.248368                0.077124   
std                 0.690218                0.432517   
min                 0.000000                0.000000   
25%                 0.000000                0.000000   
50%                 0.000000                0.000000   
75%                 0.000000                0.000000   
max                13.000000               17.000000   

       Count_more_than_12_months_late  application_underwriting_score  \
count                    55897.000000                    55897.000000   
mean                         0.060289                       99.073974   
std                          0.310669                        0.723533   
min                          0.000000                       91.960000   
25%                          0.000000                       98.830000   
50%                          0.000000                       99.210000   
75%                          0.000000                       99.520000   
max                         11.000000                       99.890000   

       no_of_premiums_paid  
count         55897.000000  
mean             10.861102  
std               5.158885  
min               2.000000  
25%               7.000000  
50%              10.000000  
75%              14.000000  
max              60.000000

In [27]:
X_train.loc[:,:] = sd.transform(X_train)

In [28]:
X_train.describe()

perc_premium_paid_by_cash_credit   age_in_days        Income  \
count                      5.589700e+04  5.589700e+04  5.589700e+04   
mean                       1.189810e-16 -2.313519e-16  2.669445e-17   
std                        1.000009e+00  1.000009e+00  1.000009e+00   
min                       -9.385783e-01 -2.145369e+00 -4.528186e-01   
25%                       -8.368035e-01 -7.432228e-01 -2.467269e-01   
50%                       -4.356911e-01 -4.214982e-02 -1.010854e-01   
75%                        6.628778e-01  7.276483e-01  1.092855e-01   
max                        2.054798e+00  3.600665e+00  1.318538e+02   

       Count_3-6_months_late  Count_6-12_months_late  \
count           5.589700e+04            5.589700e+04   
mean           -1.010576e-17           -1.855900e-17   
std             1.000009e+00            1.000009e+00   
min            -3.598424e-01           -1.783160e-01   
25%            -3.598424e-01           -1.783160e-01   
50%            -3.598424e-01           -1.783160e-01   
75%            -3.598424e-01           -1.783160e-01   
max             1.847495e+01            3.912685e+01   

       Count_more_than_12_months_late  application_underwriting_score  \
count                    5.589700e+04                    5.589700e+04   
mean                     4.855848e-17                    6.529526e-15   
std                      1.000009e+00                    1.000009e+00   
min                     -1.940649e-01                   -9.832360e+00   
25%                     -1.940649e-01                   -3.372013e-01   
50%                     -1.940649e-01                    1.880040e-01   
75%                     -1.940649e-01                    6.164609e-01   
max                      3.521368e+01                    1.127845e+00   

       no_of_premiums_paid  sourcing_channel_A  sourcing_channel_B  \
count         5.589700e+04        5.589700e+04        5.589700e+04   
mean          1.417348e-17       -1.449127e-17        2.542329e-19   
std           1.000009e+00        1.000009e+00        1.000009e+00   
min          -1.717654e+00       -1.085880e+00       -5.106733e-01   
25%          -7.484439e-01       -1.085880e+00       -5.106733e-01   
50%          -1.669177e-01        9.209121e-01       -5.106733e-01   
75%           6.084505e-01        9.209121e-01       -5.106733e-01   
max           9.525185e+00        9.209121e-01        1.958199e+00   

       sourcing_channel_C  sourcing_channel_D  sourcing_channel_E  \
count        5.589700e+04        5.589700e+04        5.589700e+04   
mean         5.656681e-17        2.453347e-17       -8.135452e-18   
std          1.000009e+00        1.000009e+00        1.000009e+00   
min         -4.210400e-01       -3.221298e-01       -8.669615e-02   
25%         -4.210400e-01       -3.221298e-01       -8.669615e-02   
50%         -4.210400e-01       -3.221298e-01       -8.669615e-02   
75%         -4.210400e-01       -3.221298e-01       -8.669615e-02   
max          2.375072e+00        3.104338e+00        1.153454e+01   

       residence_area_type_Rural  residence_area_type_Urban  
count               5.589700e+04               5.589700e+04  
mean               -1.662683e-16              -1.703360e-17  
std                 1.000009e+00               1.000009e+00  
min                -8.117635e-01              -1.231886e+00  
25%                -8.117635e-01              -1.231886e+00  
50%                -8.117635e-01               8.117635e-01  
75%                 1.231886e+00               8.117635e-01  
max                 1.231886e+00               8.117635e-01

In [29]:
X_test.describe()

perc_premium_paid_by_cash_credit   age_in_days        Income  \
count                      23956.000000  23956.000000  2.395600e+04   
mean                           0.316005  18849.337786  2.104672e+05   
std                            0.336869   5207.693705  6.604547e+05   
min                            0.000000   7670.000000  2.403000e+04   
25%                            0.033000  14975.000000  1.080475e+05   
50%                            0.166000  18625.000000  1.655600e+05   
75%                            0.543250  22636.000000  2.501225e+05   
max                            1.000000  37240.000000  9.026260e+07   

       Count_3-6_months_late  Count_6-12_months_late  \
count           23956.000000            23956.000000   
mean                0.248372                0.080356   
std                 0.693175                0.444842   
min                 0.000000                0.000000   
25%                 0.000000                0.000000   
50%                 0.000000                0.000000   
75%                 0.000000                0.000000   
max                11.000000               14.000000   

       Count_more_than_12_months_late  application_underwriting_score  \
count                    23956.000000                    23956.000000   
mean                         0.059108                       99.069414   
std                          0.314560                        0.733033   
min                          0.000000                       91.900000   
25%                          0.000000                       98.830000   
50%                          0.000000                       99.210000   
75%                          0.000000                       99.520000   
max                          8.000000                       99.890000   

       no_of_premiums_paid  
count         23956.000000  
mean             10.870387  
std               5.198223  
min               2.000000  
25%               7.000000  
50%              10.000000  
75%              14.000000  
max              58.000000

In [30]:
X_test.loc[:,:] = sd.transform(X_test)

In [31]:
X_test.describe()

perc_premium_paid_by_cash_credit   age_in_days        Income  \
count                      23956.000000  23956.000000  23956.000000   
mean                           0.007343      0.000724      0.005692   
std                            1.008374      0.999719      1.624275   
min                           -0.938578     -2.145369     -0.452819   
25%                           -0.839797     -0.743031     -0.246192   
50%                           -0.441678     -0.042342     -0.104750   
75%                            0.687573      0.727648      0.103217   
max                            2.054798      3.531172    221.473472   

       Count_3-6_months_late  Count_6-12_months_late  \
count           23956.000000            23956.000000   
mean                0.000006                0.007472   
std                 1.004293                1.028505   
min                -0.359842               -0.178316   
25%                -0.359842               -0.178316   
50%                -0.359842               -0.178316   
75%                -0.359842               -0.178316   
max                15.577291               32.190643   

       Count_more_than_12_months_late  application_underwriting_score  \
count                    23956.000000                    23956.000000   
mean                        -0.003802                       -0.006302   
std                          1.012533                        1.013139   
min                         -0.194065                       -9.915287   
25%                         -0.194065                       -0.337201   
50%                         -0.194065                        0.188004   
75%                         -0.194065                        0.616461   
max                         25.557023                        1.127845   

       no_of_premiums_paid  sourcing_channel_A  sourcing_channel_B  \
count         23956.000000        23956.000000        23956.000000   
mean              0.001800           -0.006253           -0.000533   
std               1.007634            1.000517            0.999635   
min              -1.717654           -1.085880           -0.510673   
25%              -0.748444           -1.085880           -0.510673   
50%              -0.166918            0.920912           -0.510673   
75%               0.608451            0.920912           -0.510673   
max               9.137501            0.920912            1.958199   

       sourcing_channel_C  sourcing_channel_D  sourcing_channel_E  \
count        23956.000000        23956.000000        23956.000000   
mean             0.001715            0.007415            0.006444   
std              1.001694            1.010257            1.036233   
min             -0.421040           -0.322130           -0.086696   
25%             -0.421040           -0.322130           -0.086696   
50%             -0.421040           -0.322130           -0.086696   
75%             -0.421040           -0.322130           -0.086696   
max              2.375072            3.104338           11.534538   

       residence_area_type_Rural  residence_area_type_Urban  
count               23956.000000               23956.000000  
mean                   -0.004148                   0.004148  
std                     0.999140                   0.999140  
min                    -0.811764                  -1.231886  
25%                    -0.811764                  -1.231886  
50%                    -0.811764                   0.811764  
75%                     1.231886                   0.811764  
max                     1.231886                   0.811764

# formatting target column if required

In [32]:
Y.dtypes

dtype('int64')

In [33]:
Y.value_counts()

target
1    74854
0     4999
Name: count, dtype: int64

In [71]:
Y.value_counts(normalize=True)

target
1    0.937397
0    0.062603
Name: proportion, dtype: float64

In [34]:
Y.unique()

array([1, 0], dtype=int64)

# feature selection using pca

In [35]:
from sklearn.decomposition import PCA
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_selection import SelectFromModel

In [36]:
pca = PCA(n_components = 0.95, random_state=7)
pca.fit(X_train)

PCA(n_components=0.95, random_state=7)

In [37]:
pca.n_components_

12

In [38]:
pca.components_

array([[ 2.29505846e-03,  6.44127813e-03,  9.21642971e-03,
         6.00486796e-03, -4.16185942e-03, -5.44239733e-03,
        -3.18992894e-05,  1.33879089e-02, -1.62601206e-02,
         2.02533640e-02, -5.01020210e-05,  4.19599527e-03,
        -1.51960203e-02, -7.06640979e-01,  7.06640979e-01],
       [ 3.98743750e-01, -3.49261731e-01, -2.91880871e-03,
         3.41562307e-01,  3.10697012e-01,  3.21874970e-01,
        -1.49613494e-01, -5.13123283e-02, -4.75580454e-01,
         2.00718788e-01,  2.63561983e-01,  1.99477971e-01,
         3.72886688e-02,  6.38084514e-03, -6.38084514e-03],
       [-2.70795821e-01,  4.75837242e-02,  1.66486500e-01,
        -2.53112518e-01, -3.41237352e-01, -3.26112504e-01,
        -5.41435573e-02,  2.55407063e-01, -5.58427339e-01,
         4.14547791e-01,  2.08753209e-01,  1.10163365e-01,
         4.12529979e-02,  1.67104721e-02, -1.67104721e-02],
       [-6.13563315e-02,  3.74857937e-01,  5.69956847e-02,
         3.43988356e-01,  5.91939662e-02,  2.33125844

In [39]:
X_train_pca = pca.transform(X_train)
X_test_pca = pca.transform(X_test)

# feature selection using decision tree

In [40]:
dt = DecisionTreeClassifier(criterion='gini', random_state=7, class_weight='balanced')

In [41]:
dt.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight='balanced', random_state=7)

In [42]:
dt.feature_importances_

array([0.28957681, 0.15187438, 0.1478954 , 0.06701284, 0.05690162,
       0.02455394, 0.12842434, 0.07992456, 0.0112041 , 0.01023865,
       0.008988  , 0.00701607, 0.00120744, 0.00865684, 0.00652501])

In [43]:
feature_tup = tuple(zip(X_train.columns, dt.feature_importances_))

In [44]:
sorted(feature_tup, key = lambda x : -x[1])

[('perc_premium_paid_by_cash_credit', 0.2895768133987442),
 ('age_in_days', 0.1518743835210055),
 ('Income', 0.14789540015896285),
 ('application_underwriting_score', 0.12842434020122767),
 ('no_of_premiums_paid', 0.07992455612116915),
 ('Count_3-6_months_late', 0.06701284150189889),
 ('Count_6-12_months_late', 0.05690161804211017),
 ('Count_more_than_12_months_late', 0.02455394187393631),
 ('sourcing_channel_A', 0.011204095624425071),
 ('sourcing_channel_B', 0.010238645101349605),
 ('sourcing_channel_C', 0.008988000384995184),
 ('residence_area_type_Rural', 0.008656839818645536),
 ('sourcing_channel_D', 0.007016073524857392),
 ('residence_area_type_Urban', 0.0065250126458957815),
 ('sourcing_channel_E', 0.0012074380807768038)]

In [45]:
sel = SelectFromModel(DecisionTreeClassifier(criterion='gini', random_state=7, class_weight='balanced'),threshold='mean')

In [46]:
sel.fit(X_train, Y_train)

SelectFromModel(estimator=DecisionTreeClassifier(class_weight='balanced',
                                                 random_state=7),
                threshold='mean')

In [47]:
sel.get_feature_names_out

<bound method SelectorMixin.get_feature_names_out of SelectFromModel(estimator=DecisionTreeClassifier(class_weight='balanced',
                                                 random_state=7),
                threshold='mean')>

In [48]:
X_train_DT = sel.transform(X_train)

In [49]:
X_test_DT = sel.transform(X_test)

In [50]:
sel.get_feature_names_out(X_train.columns)

array(['perc_premium_paid_by_cash_credit', 'age_in_days', 'Income',
       'Count_3-6_months_late', 'application_underwriting_score',
       'no_of_premiums_paid'], dtype=object)

In [51]:
sel.estimator_.feature_importances_

array([0.28957681, 0.15187438, 0.1478954 , 0.06701284, 0.05690162,
       0.02455394, 0.12842434, 0.07992456, 0.0112041 , 0.01023865,
       0.008988  , 0.00701607, 0.00120744, 0.00865684, 0.00652501])

In [52]:
X_train.columns

Index(['perc_premium_paid_by_cash_credit', 'age_in_days', 'Income',
       'Count_3-6_months_late', 'Count_6-12_months_late',
       'Count_more_than_12_months_late', 'application_underwriting_score',
       'no_of_premiums_paid', 'sourcing_channel_A', 'sourcing_channel_B',
       'sourcing_channel_C', 'sourcing_channel_D', 'sourcing_channel_E',
       'residence_area_type_Rural', 'residence_area_type_Urban'],
      dtype='object')

# RFE

In [53]:
from sklearn.feature_selection import RFE

In [54]:
rfe = RFE(DecisionTreeClassifier(criterion='gini',random_state=7,class_weight='balanced'),
          n_features_to_select =0.5)

In [55]:
rfe.fit(X_train,Y_train)

RFE(estimator=DecisionTreeClassifier(class_weight='balanced', random_state=7),
    n_features_to_select=0.5)

In [56]:
rfe.ranking_

array([1, 1, 1, 1, 1, 2, 1, 1, 5, 6, 4, 7, 9, 3, 8])

# Logistic Regression

In [57]:
from sklearn.linear_model import LogisticRegression

In [58]:
lr = LogisticRegression(class_weight="balanced", random_state=7, solver='saga')

In [59]:
lr.fit(X_train, Y_train)

LogisticRegression(class_weight='balanced', random_state=7, solver='saga')

In [60]:
lr.coef_

array([[-6.57378173e-01,  2.61140167e-01,  1.18721195e-01,
        -3.74104625e-01, -4.62772076e-01, -2.87347807e-01,
         1.67267610e-01, -1.65405152e-01,  7.73587775e-03,
         2.93018999e-02, -2.35150498e-02, -2.49818231e-02,
        -2.63034824e-04, -1.19611761e-02,  1.19611761e-02]])

In [61]:
Y_pred = lr.predict(X_test)

In [62]:
Y_test.shape, Y_pred.shape

((23956,), (23956,))

In [63]:
from sklearn.metrics import classification_report
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.18      0.72      0.29      1505
           1       0.98      0.79      0.87     22451

    accuracy                           0.78     23956
   macro avg       0.58      0.75      0.58     23956
weighted avg       0.93      0.78      0.84     23956



In [72]:
# logistic regression is failing here bcoz data is more imbalanced, so it needs more no. of iterations

# SVM

In [64]:
from sklearn.svm import SVC

In [65]:
svc = SVC(class_weight="balanced", random_state=7)

In [66]:
svc.fit(X_train,Y_train)

SVC(class_weight='balanced', random_state=7)

In [67]:
Y_pred = svc.predict(X_test)

In [68]:
Y_test.shape, Y_pred.shape

((23956,), (23956,))

In [69]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.19      0.72      0.30      1505
           1       0.98      0.80      0.88     22451

    accuracy                           0.79     23956
   macro avg       0.59      0.76      0.59     23956
weighted avg       0.93      0.79      0.84     23956



In [73]:
# svm is showing decent performance coz of hyperspace

# Random Forest

In [70]:
from sklearn.ensemble import RandomForestClassifier

In [75]:
rfc = RandomForestClassifier(n_estimators=200, max_samples=0.6, max_depth=4, oob_score=True, class_weight='balanced',random_state=7)

In [77]:
rfc.fit(X_train_pca,Y_train)

RandomForestClassifier(class_weight='balanced', max_depth=4, max_samples=0.6,
                       n_estimators=200, oob_score=True, random_state=7)

In [78]:
Y_pred= rfc.predict(X_test_pca)

In [79]:
from sklearn.metrics import f1_score
f1_score(Y_test, Y_pred)

0.871149289099526

In [80]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.18      0.72      0.29      1505
           1       0.98      0.79      0.87     22451

    accuracy                           0.78     23956
   macro avg       0.58      0.76      0.58     23956
weighted avg       0.93      0.78      0.83     23956

